[config.wallpaper]
command = "awww img --transition-type center --transition-fps 60 --transition-step 255 \"{{image}}\""
set = true

# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/matugen/matugen-rofi.rasi'

# Waybar
[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

# Hyprlock
[templates.hyprlock]
input_path = '~/.config/matugen/templates/matugen-hyprlock.conf'
output_path = '~/.config/hypr/hyprlock/matugen/matugen-hyprlock.conf'

# Swaync
[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync/matugen/matugen-swaync.css'
post_hook = 'swaync-client -rs'

# Gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

# Gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

# nwg-dock-hyprland
[templates.nwg-dock-hyprland]
input_path = '~/.config/matugen/templates/matugen-dock.css'
output_path = '~/.config/nwg-dock-hyprland/style.css'
post_hook = 'pkill -USR1 -f nwg-dock-hyprland'
