[colors.primary]
background = '#15121c'
foreground = '#e8dfee'

[colors.selection]
text = '#e8dfee'
background = '#5a00c6'

[colors.cursor]
text = '#15121c'
cursor = '#d2bbff'

[colors.normal]
black   = '#15121c'
red     = '#ff728e'
green   = '#7fff9b'
yellow  = '#ffda72'
blue    = '#bea4f2'
magenta = '#4f3c76'
cyan    = '#d2bbff'
white   = '#f4efff'

[colors.bright]
black   = '#44414a'
red     = '#ff9fb2'
green   = '#a5ffb9'
yellow  = '#ffe7a5'
blue    = '#d8c5ff'
magenta = '#dfcfff'
cyan    = '#eae0ff'
white   = '#faf8ff'
