# Theme
# gui:
#   theme:
#     activeBorderColor:
#       - "#a6e3a1" # Green
#       - bold
#     inactiveBorderColor:
#       - "#cdd6f4" # Text
#     optionsTextColor:
#       - "#89b4fa" # Blue
#     selectedLineBgColor:
#       - "#313244" # Surface0
#     selectedRangeBgColor:
#       - "#313244" # Surface0
#     cherryPickedCommitBgColor:
#       - "#94e2d5" # Teal
#     cherryPickedCommitFgColor:
#       - "#89b4fa" # Blue
#     unstagedChangesColor:
#       - red # Red
gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#5ef1ff"
    inactiveBorderColor:
      - "#7b8496"
    searchingActiveBorderColor:
      - "#ff5ef1"
    optionsTextColor:
      - "#3c4048"
    selectedLineBgColor:
      - "#3c4048"
    cherryPickedCommitBgColor:
      - "#3c4048"
    cherryPickedCommitFgColor:
      - "#ff5ea0"
    unstagedChangesColor:
      - "#ffbd5e"
    defaultFgColor:
      - "#ffffff"
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
git:
  parseEmoji: true
customCommands:
  - key: "Z"
    command: "czg"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "O"
    command: 'nvim -c ":Octo pr create"'
    context: "localBranches"
    loadingText: "Opening Octo..."
    subprocess: true
