
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000

# Sets user-defined palette
palette = "rose-pine"

# format = """
# $directory\
# $git_branch\
# $git_status
# """
#

right_format = """
$time\
$cmd_duration\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[\uf054](green)" # 
vicmd_symbol = "[\ue62b](green)"   # 
error_symbol = "[\uf467](red)"     # 

[time]
disabled = false

[os]
disabled = false

[gcloud]
disabled = true

[directory]
read_only = " 󰌾"
disabled = false
truncate_to_repo = false
style = "bold lavender"

[package]
symbol = "󰏗 "
disabled = true

[username]
disabled = false
show_always = true

[hostname]
ssh_symbol = " "
disabled = true

[aws]
symbol = "  "
disabled = true

[docker_context]
symbol = " "
disabled = true

[git_branch]
# symbol = " "
symbol = "󰊢 "

[git_commit]
disabled = false

[git_state]
disabled = false
rebase = "rebasing"
merge = "  merging"
revert = " 󰕍 reverting"
cherry_pick = "  picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"

[git_metrics]
disabled = false

[git_status]
disabled = true
stashed = "   ${count}"
ahead = " 󰞙  ${count}"
behind = " 󰞖  ${count}"
diverged = " 󰓢 ${ahead_count} ${behind_count}"
conflicted = "   ${count}"
deleted = "   ${count}"
renamed = " 󰗧 ${count}"
modified = "   ${count}"
staged = "   ${count}"
untracked = " 󰧮 ${count}"

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "


# palette tables should be last in the config ⚓️
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
