# Generated by nixos-generate-config on the target machine.
# To regenerate: nixos-generate-config --show-hardware-config > hardware-configuration.nix
# This placeholder allows `nix flake check` to pass before first deployment.
{ ... }: {}
