# Autostart necessary processes
exec-once = hypridle
exec-once = awww-daemon
exec-once = waybar
exec-once = swaync
exec-once = vicinae server
exec-once = avizo-service # Volume/Brightness OSD
exec-once = easyeffects --gapplication-service
