# Set programs that you use
$terminal = ghostty
$fileManager = nautilus
$menu = rofi -show run
$browser = zen-browser
$music = spotify-launcher
$social = rambox
$notes = obsidian

# Script directories
$hyprScripts = $HOME/.config/hypr/scripts
$rofiScripts = $HOME/.config/rofi/scripts
