# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

# Source all modules
source = $HOME/.config/hypr/modules/variables.conf
source = $HOME/.config/hypr/modules/environment.conf
source = $HOME/.config/hypr/modules/monitors.conf
source = $HOME/.config/hypr/modules/autostart.conf
source = $HOME/.config/hypr/modules/input.conf
source = $HOME/.config/hypr/modules/layouts.conf
source = $HOME/.config/hypr/modules/appearance.conf
source = $HOME/.config/hypr/modules/animations.conf
source = $HOME/.config/hypr/modules/keybindings.conf
source = $HOME/.config/hypr/modules/windowrules.conf
