# Generated by nixos-generate-config on the target machine.
# To regenerate: nixos-generate-config --show-hardware-config > hardware-configuration.nix
# Replace this file with the real hardware config on the T480.
{ ... }: {}
