require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.nvim-tmux-navigator"
require "user.rayx-gonvim"
require "user.dapui"
require "user.telescope_dap"
require "user.notify"

if vim.g.vscode then
  vim.cmd 'source $HOME/.config/nvim/vscode/settings.vim'
end
